---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    MONGO_URI: {{  required "secrets.backend.mongoUri is required" .Values.secrets.backend.mongoUri }} #.Values.secrets.backend.mongoUri
  template:
    metadata:
      name: mongo-secret
      namespace: {{ .Release.Namespace }}
