---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secret
  namespace: taskflow-ns
spec:
  encryptedData:
    MONGO_URI: AgCw0AND8hiUHDr16LzvzGMXoeXPoGF4Jd3szOTSnnQBeXApnCh2LoEX+4QqDZr5MGFlas9XAfKr1L5r7XLnwFoMae2vBo+r3ztlrxHnXp7wwgtfV4f04Cgs6PfjAyA/UEOLj+xtC77AuZ2sk2rP/HxdNnQB4HYPCNY2/kPbo/ykUVAcM9dEKSqY3hayJEjQxBfbjbXNYpISTvdr4AfHSRPLLM4S3UupfNMDF0KaV+s4fvCPvAG3gAeqoZbhzb2i27Z322WAFYceyDAujPGNG4dpUmdOUspVcA5u+8fs2+EQJ8z6FDRxPnHdwR4o8r3P/zVomDIo2UYsc+ZCmrW56O3PqlPBTYlKPmFv0eRVfBieIGq4JQAz6BOIQVsccuOIrk7YvdgjAZYOzp1x6R1cbWU5Syw3nUvM8SwZxRcel6dw92w3LgWYro4rFOP+6T9jzwQUfsA4WVH1NRhZ05Xr8Iu5N8sBwA884lfFnt7/cin4LpxQp2GaDEpKBgdyGTHJblN4iFhI0TcNZLjBnEPIv2qVWwkEUvXHMG/rTWwm82GHIQGB+aknfHRNNHDE3V/S9gDLB/PtweGuH0MTJmlH/So12r76xSYTdcsjD8qz72KY8JXfAcNVTdXSHOeRJSxN9oTvFZGVJQ8t9txNxcVoBXfrU/XRNfWllpIEjpbRNwdi6GdRask8wVPjAQd00vOkkuPp5isVcps+PuBMS9hfJuakqgW0FoSimoNni4FujHEXODy5abClCmR8GVofMLVN142KZt0dU5lW0bgJM0FzC+YN35EdymB9JSAPz4vRWoe/FlcxQ9b9g9/Fv1kkWJae1ufchxPOZ33VcN4=
  template:
    metadata:
      name: mongo-secret
      namespace: taskflow-ns
