taskflow_frontend:
  replicaCount: 1
  image:
    repository: princewillopah2/taskflow-app_frontend
    tag: 1.1.6
    pullPolicy: IfNotPresent
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  port: 80
  nodePort: 30080
  service:
    type: ClusterIP # or NodePort, LoadBalancer, etc.
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
