apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.taskflow_frontend.port }}
      targetPort: {{ .Values.taskflow_frontend.port }}
      # nodePort: {{ .Values.taskflow_frontend.nodePort }}
      {{- if eq .Values.taskflow_frontend.service.type "NodePort" }}
      nodePort: {{ .Values.taskflow_frontend.nodePort }}
      {{- end }}
    - name: metrics                  # MUST match ServiceMonitor
      port: 9113
      targetPort: 9113