# global:
taskflow_secrets:
  # secrets values
  secrets:
    backend:
      mongoUri: AgB+Bl38CV0JhBzvZWv0GFy/IHam+fRWFqbOTOededS8SB9T0NlNN++u74wdsF2iu6KARoGjw+NZ/oEQer2BMWiHFIwG7AEcdgSFtEMechDtAeAIgS5hkzSfD+Gp0Y1myVWuZ46zDRq2vHTKaHSJ4J33COlnl/HEsa90Ylz9rpb2F+rrkx2PSBkTAU7UkjRDEhmBv5LU1rnpcdPp0oSwQnKXiG0HdpCxvBjzBNtNIJfTf7CzVq1NGbPtIapMx7naipGVl6j8o1Mr/T7KBa02cPeFYGnJwbudmNC18MrrX3Jj9LlBkQEcHv8WgXnABG1nvE1kDYCj0mPexqmb67l0yUAv9BnkonjW2jjsgAAwfBAfmSNVmXhZaDzZs+pqw6YwbpulGtfJJ0C8W92KXkXOZ4Kn/xX4GsNjPp6WacDIfaJnfp0PGu9mHzTh/j88E1HkEsTjERMfS64JXWnUqE7pikSP3kR3TGLg3rm6giYeXGhhMVyBq1YQVxN7Wsz3aLM6omyFnvRYr8w+CzOonG+466Q164S5nEG9osimCLSQ1QljAHjI9IpRqHDAJ6sgBVcz1NDXFzxfmPoAYfhqatthhHiRMQ3BFf+HqzpE1Kb8ECtZTJcGGzpfo8Nr7XEBW7PPLCku3z733gxylFHj9apn0hkDEEuG2e6Hlvz9jDI2TYHifB4SqygvHc6x+39ZqZOMgd1VItBfJIFRGLeFF3+nQ8gfrJG3PKclQrqRudKduwuBb0jwfl6BkLb+9LvOikbawIZp+fmtwrX0v7C5vQbteQ9Uw73u5xclaiOSTYg60GZB3KVEvrQVpAIz8BEAOpb9V+9fJ8PEUeejLA==

  # network policy values
  taskflow_network_policies:
    backend:
      port: 3000

    node_exporter:
      port: 9113

# backend values here
taskflow_backend:
  image:
    repository: princewillopah2/taskflow-app_backend
    tag: dev_1.1.6
    pullPolicy: IfNotPresent
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  port: 3000
  # nodePort: 30080  # NodePort for development environment
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true





# frontend values here
taskflow_frontend:
  image:
    repository: princewillopah2/taskflow-app_frontend
    tag: dev_1.1.6
    pullPolicy: IfNotPresent
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  port: 80
  # nodePort: 30080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"


